name = "cloudflare-ai-chat-upgraded"
main = "src/worker.js"
compatibility_date = "2025-05-25" # Or newer
compatibility_flags = ["nodejs_compat"] # If using Node.js APIs like crypto

# Add your D1 binding
[[d1_databases]]
binding = "DB" # How you'll access it in your Worker (e.g., env.DB)
database_name = "your-d1-database-name"
database_id = "your-d1-database-id"

[vars]
# It's better to set secrets via Cloudflare Dashboard:
# AI_API_KEY_1 = "your_gemini_api_key_1" (Store in D1 instead via admin panel)
# AI_API_KEY_2 = "your_gemini_api_key_2" (Store in D1 instead via admin panel)
APP_SECRET = "a_very_strong_random_secret_for_sessions_etc" # Generate a strong random string

# Turnstile keys (get these from your Cloudflare dashboard)
# These can also be set as secrets in the dashboard
TURNSTILE_SITE_KEY = "1x00000000000000000000AA" # Example public site key
# TURNSTILE_SECRET_KEY should be a secret variable set in the dashboard.

# Example of setting a secret for the Turnstile secret key:
# Run: wrangler secret put TURNSTILE_SECRET_KEY
# Then enter your secret key.

# To enable Node.js modules if needed (like 'crypto' for password hashing more easily)
[node_compat]
enable = true